export const mainTheme = {
  'color-white': '#ffffff',
  'color-dark-white': '#ffffffb3',
  'color-black': '#070707',
  'color-error': '#e93e36',
  'color-background': '#24292E',
  'color-dark-gray': '#282F36',
  'color-light-gray': '#2D353D',
  'font-xs': '12px',
  'font-sm': '14px',
  'font-md': '16px',
  'font-lg': '20px',
  'font-xl': '25px',
  'border-sm': 'solid 1px #ffffff1f',
  'border-md': 'solid 2px #ffffff1f',
  'border-lg': 'solid 3px #ffffff1f',
  'border-hover': 'solid 1px #bdbdbd',
  'border-error': '1px solid #e93e36',
  'rounded-sm': '5px',
  'rounded-md': '10px',
  'rounded-lg': '15px',
  'rounded-full': '9999px',
  'box-shadow': '0px 6px 15px -2px rgba(0, 0, 0, 0.2)',
  'text-shadow': '0px 2px 5px rgba(0, 0, 0, 0.3)',
};

export type ThemeType = typeof mainTheme;
